### ISSUE TITLE
Remove "Not available in Python bindings" from c++ docs?

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGISPythonAPIDocumentation#7]
Related to this work - I've been wondering whether we should drop all the doxygen "Not available in Python bindings" notes from the c++ docs and headers. To me this information seems redundant now - either it's available in the bindings and included in the Python docs, or it's not and it won't be in the Python docs. This information was really just a hack while we only had c++ docs available for Python devs.

**Comment by 3nids** [comment]
I'm not sure about this. It just makes it more obvious while reading the code and of course the cpp doc.

**Comment by nyalldawson** [comment]
Isn't the "SIP_SKIP" indication enough when reading the code?

**Comment by 3nids** [comment]
sometimes yes, sometimes you just have big #ifdef SIP_RUN blocks which are
really not obvious

Le lun. 22 janv. 2018 à 19:56, Nyall Dawson <notifications@github.com> a
écrit :

**Comment by nyalldawson** [comment]
Up to you I guess -- close this if you think it's not an issue

**Comment by 3nids** [comment]
I don't really mind, I thought it might be easier for others to spot on this. @timlinux?
